### ISSUE TITLE
Error to combile kcbench on Ubuntu 18.04

### ISSUE THREAD

**Issue by adityacloud1** [knurd/kcbench#4]
Respected all,
To compile the kernel benchmark on Ubuntu 18.04 with _make and gcc installed_, i followed instructions as per the manual. 
After running following commands, the error encountered is:
``root@c1:~# sudo bash kcbench
Linux running:      4.15.0-39-generic on x86_64 (c1)
Processor Cores:    8 -- Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Compiler:           gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Linux compiled:     4.14 (/home/ubuntu/.cache/kcbench/linux-4.14)
Run 1 (-j 16):      Failed (Mon Nov 19 16:22:14 UTC 2018).
Hit 'l' within 300 seconds to view log-file.``

Pls suggest how to resolve this error.

**Comment by knurd** [comment]
Did you hit the "L"  key to show the log-file? It might be helpful to diagnose this problem. There is also a commandline switch (see kcbench --help) to write the log to some file and look at it.

Anyway: There is something suspicious in the output: "Compiler: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609" is afaics not the default compiler in 18.04 (it uses 7.3 iirc), which might or might not be the reason for the problem. Check you compiler installations and make sure "gcc" calls the ubuntu compiler; you can also specify a different compiler using a command line switch

**Comment by adityacloud1** [comment]
Thanks for the response. The problem was due to **bcc package**
Got resolved using
`sudo apt-get install bc`
